Controllers films users
stanislavma/java-filmorate pull request #5
Opened 2024-03-06 20:45 UTC by stanislavma

2024-03-07 17:31 UTC, TomattmanYandex requested changes
комментарии в коде

2024-03-07 17:31 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public ResponseEntity<?> add(@Valid @RequestBody Film film) {
обычно конкретные методы параметризуют  конкретными объектами, 
Например тут в любом случае будет возвращаться фильм, следовательно следует возвращать ResponseEntity<Film>

2024-03-07 17:31 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private int id;
Лучше использовать класс обертку вместо примитива
он может содержать значение null что будет значить что значение не проставлено, а с примитивом будет значение по умолчанию, и ты не сможешь понять это реальное значение, или просто по умолчанию

2024-03-07 17:31 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +public class User {
и комментарии те же что и у фильма + новые

2024-03-07 17:31 UTC, TomattmanYandex commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +    void shouldAdd() throws Exception {
обычно тестовые методы именуют следующим образом
названеТестируемогоМетода_чтоДолжноПроизойти_приКакихУсловиях
последняя часть опциональна
например
add_operationSuccessfull_filmIsValid
add_operationSuccessfull
add_throwValidationException_filmIsNotValid

есть разные вариации именования, я считаю эту одной из лучших, но в любом случае, хорошее имя содержит название тестируемого метода

2024-03-07 17:31 UTC, TomattmanYandex commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +        Film film = Film.builder()
Протестировать надо было валидацию а не методы контроллера
методы добавления проверяет валидацию так что все норм, и есть тест на негативные случает так что все хорошо

2024-03-08 04:46 UTC, stanislavma commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private short duration;
Сделал short, потому что подумал что Integer избыточен для продолжительности фильма. Получается сделал для экономии памяти.

2024-03-08 23:11 UTC, TomattmanYandex approved these changes
Принято

2024-03-09 06:45 UTC, merged