Add friends likes
stanislavma/java-filmorate pull request #6
Opened 2024-03-21 20:28 UTC by stanislavma

2024-03-22 16:55 UTC, TomattmanYandex requested changes
Привет, хорошая работа, в коде есть пара ошибок и пара рекомендаций

2024-03-22 16:55 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public FilmController(FilmService filmService) {
Вместо того, чтобы писать контроллер вручную, можно использовать аннотацию @RequredArgsConstructor

2024-03-22 16:55 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/model/ErrorResponse.java
> +    String error;
Модификаторов доступа не хватает

2024-03-22 16:55 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public FilmService(FilmStorage filmStorage, UserService userService) {
аналогично как в контроллере

2024-03-22 16:55 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmStorage.java
> +    Film add(Film film);
я бы порекомендовал оставить в репозитории только метод на сохранение, обновление, получение одного по идентификатору и получению всех (ну и можно если надо какие то методы получения с фильтрами) и удаление
обычно это называется CRUD операции и через них уже можно построить всю логику

а все остальное сделать логикой в сервисе
например isExist
это в сервисе storage.getById() != null

2024-03-22 16:55 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/UserStorage.java
> +public interface UserStorage {
тут аналогично

2024-03-22 16:55 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/util/ResponseUtil.java
> +//    public static <T> ResponseEntity<T> respondError(T body, HttpStatus httpStatus) {
закомментированный код не допускается

2024-03-22 17:57 UTC, stanislavma commented
Привет. Спасибо за review, исправил код по твоим рекомендациям.

2024-03-23 13:39 UTC, TomattmanYandex approved these changes
Привет, один небольшой комент, можно к следующему спринту поправить

2024-03-23 13:39 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/model/ErrorResponse.java
> +package ru.yandex.practicum.filmorate.model;
обычно к моделям относятс то, что является доменной моделью проекта, чаще всего это то что мы храним
сообщения об ошибках к нм не относятся, следовательно лучше переместить в другой пакет
есть такая штука как Dto data transfer object это обьекты, которые нужны только для передачи между слоями приложения или вообще между приложениями, рекомендую создать пакет dto и поместить этот класс туда

2024-03-23 14:05 UTC, merged