Add database
stanislavma/java-filmorate pull request #7
Opened 2024-04-17 07:56 UTC by stanislavma

2024-04-17 13:32 UTC, TomattmanYandex requested changes
Привет, отличная работа:
Комментарии в коде, но в основном по всяких оптимизациям
+ по условию должна быть картинка со схемой базы данных

2024-04-17 13:32 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controller/MpaController.java
> +@RequestMapping("mpa")
тяжеловато воспринимается из-за того что в начале нету /
но думаю это сила привычки

2024-04-17 13:32 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    public Map<String, Object> toMap() {
обычно в модель такое не добавляют, модель отвечает только за представление обьектов
лучше этот метод сделать в хранилище

2024-04-17 13:32 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        return mpaStorage.getAll().stream()
чаще для такого делают следующим образом 
метод возвращающий по идентификатору, делают чтобы возвращал не сам объект а Optional с этим объектом, а дальше у Optional вызывают orElseThrow ну или если возвращается сам объект то object == null
текущий же вариант плох тем, что будут возвращаться все рейтинги, 
Обычно самое узкое место в быстродействии это взаимодействие с базой и чаще именно его стараются оптимизировать в первую очередь, например не делать лишних запросов, или чтобы вопросы содержали только нужную минимальную информацию

2024-04-17 13:32 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        validateIsExist(id);
тут лишние запросы к базе, т.е. мы сначала получаем все фильмы чтобы проверить существует ли фильм, а потом получаем конкретный, как это поправить, будет комментарий ниже

2024-04-17 13:32 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/GenreService.java
> +    public Genre getById(long id) {
оптимизация этого метода (подойдет как эталонное решение для всех таких моментов
если storage возвращает сам объект то
public Genre getById(long id) {
  Genre genre = genreStorage.getById(id);
  if(genre == null) {
      String errorText = "Жанр с таким Id не найден: " + id;
      log.error(errorText);
      throw new EntityNotFoundException(errorText);
  }
  return genre;
}

Если сделаешь чтобы хранилище возвращало Optional то еще проще
public Genre getById(long id) {
  return genreStorage.getById(id).orElseThrow(и тут создаешь ошибку);//логирование можно добавить тут же, либо вообще на уровне контроллера в exception хендлере
}

2024-04-17 13:32 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/db/DbFilmStorageImpl.java
> +            String sqlQuery = "update film set " +
тут бы еще как ни будь обновлять mpa и жанры (если это не сделано на уровне сервиса)

2024-04-17 13:32 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/db/DbFilmStorageImpl.java
> +            String sqlQuery = "update film set " +
ok mpa обновляются а жанры нет

2024-04-17 13:32 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/db/DbFilmStorageImpl.java
> +            String sqlQuery = "delete from film where id = ?";
если не настроено каскадное удаление, и база сделана хорошо, со связями, то будет ошибка

2024-04-17 13:32 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/db/DbFilmStorageImpl.java
> +                    "STRING_AGG(g.id, ', ') AS genres_ids, " +
интересный вариант реализации

2024-04-17 13:32 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/db/DbFilmUserLikeStorageImpl.java
> +public class DbFilmUserLikeStorageImpl implements FilmUserLikeStorage {
а как лайки просматриваются, не вижу таких методов

2024-04-17 13:32 UTC, TomattmanYandex commented on src/main/resources/data.sql
> +DELETE FROM FILM_GENRE WHERE id > 0;
а зачем условие про идентификаторы?

2024-04-17 16:10 UTC, stanislavma commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/db/DbFilmStorageImpl.java
> +            String sqlQuery = "delete from film where id = ?";
Настроено каскадное удаление для фильмов и пользователей

2024-04-17 16:41 UTC, stanislavma commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/db/DbFilmUserLikeStorageImpl.java
> +public class DbFilmUserLikeStorageImpl implements FilmUserLikeStorage {
Добавил endpoint getLikes в FilmController

2024-04-18 13:26 UTC, TomattmanYandex requested changes
Привет, все хорошо, добавил еще пару моментов на улучшение, они не обязательные, но как минимум разобраться в них стоит, если сдашь буз них в следующий раз приму и так

2024-04-18 13:26 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        validateIsExist(id);
смотри, с текущим исправлением, ты делаешь два запроса одинаковых когда пытаешься получить фильм по идентификатору
сначала ты получаешь его и проверяешь на наличие, а оптом снова получаешь его  и в новом получении часть
.orElse(null); не имеет смысла, так как она не выполнится никогда, я уже писал как это сделать лучше
 
return filmStorage.getById(id).orElseThrow(() -> {
                    String errorText = "Фильм с таким Id не найден: " + id;
                    log.error(errorText );
                    return new EntityNotFoundException(errorText);
                });

2024-04-18 13:26 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        validateIsExist(id);
таким образом, 
во первых ты не плодишь дополнительных методов
во вторых делаешь только один запрос в базу
а потом если тебе надо будет проверить что фильм существует,
то вызов этого метода, автоматически прокинет ошибку если его не будет найдено, а если будет найден, и он нужен дальше для использования, метод вернет этот фильм и можно его использовать вместо проверки

2024-04-18 13:26 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        validateIsExist(id);
я оставлю ниже коммент как это использовать

2024-04-18 13:26 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
>      public Film addLike(long id, long userId) {
весь этот метод может выглядеть так
public Film addLike(long filmId, long userId) {
  Film film = getById(id); //если фильма нету то метод сам пробросит ошибку
  userService.getById(userId); //то же что и выше
  filmUserLikeStorage.addLike(id, userId); //добавляем лайк от существующего пользователя существующему фильму
  return film; //вот этот вопрос надо ли возвращать фильм при добавлении лайков, если в нем не содержится лайков, но это уже не важно
}

2024-04-18 16:46 UTC, stanislavma commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        validateIsExist(id);
Спасибо за уточнение, я что-то в первый раз не понял до конца

2024-04-18 17:02 UTC, stanislavma commented
Спасибо за ваши комментарии и предложения!

2024-04-19 15:11 UTC, TomattmanYandex approved these changes
Принято

2024-04-19 17:13 UTC, merged